### ISSUE TITLE
Create a product roadmap

### ISSUE THREAD

**Issue by lhalvesf** [lhalvesf/learn-pozzoli#1]
Create a roadmap to cover which features will be on app.

- [ ] A list of requirements that must be implemented on first version of app.
- [ ] A list of nice to have improvings for next releases.
- [ ] Define which kind of versioning approach will be used.
- [ ] Create a simple wireframe to be used as guidance for UI and features.
